### ISSUE TITLE
Install should register path

### ISSUE THREAD

**Issue by lee-40square** [strongloop/strongloop#194]
This may only apply to Ubuntu installs but would be nice to have `export PATH=/root/npm/bin:$PATH` added to .bashrc in the install.

**Comment by rmg** [comment]
That is the purpose of the `-g` in `npm install -g strongloop`. If that does not put `slc` somewhere in your PATH then node and/or npm are not installed correctly. 

How did you install node?

**Comment by lee-40square** [comment]
I installed Node through nvm. And of course `npm install -g strongloop`

**Comment by sam-github** [comment]
@lee-40square I run Ubuntu, and haven't had any issues. We'll need more info! How did you install node,  what is your `$PATH`, and where is node, `which node`, and npm, `which npm`, and what is your npm config: `npm config list`.

**Comment by lee-40square** [comment]
I really don't know what to say. This is the 4th bare metal Ubuntu box I've launched and it's working fine mostly.

* Launch a new box on AWS with Ubuntu 14.04.1 LTS
* Install nvm `curl https://raw.githubusercontent.com/creationix/nvm/v0.23.3/install.sh | bash`
* Install node `nvm install 0.12.0` (This is new today. I've been using an earlier version in the past)
* Install git

At this stage everything is working fine:
`ubuntu@ip-10-0-0-110:~$ which node`
`/home/ubuntu/.nvm/versions/node/v0.12.0/bin/node`

`ubuntu@ip-10-0-0-110:~$ which npm`
`/home/ubuntu/.nvm/versions/node/v0.12.0/bin/npm`

`ubuntu@ip-10-0-0-110:~$ npm config list`
`; cli configs`
`user-agent = "npm/2.5.1 node/v0.12.0 linux x64"`

`; node bin location = /home/ubuntu/.nvm/versions/node/v0.12.0/bin/node`
`; cwd = /home/ubuntu`
`; HOME = /home/ubuntu`

When I run `npm install -g strongloop` it throws a lot of errors but everything seems to be working fine and I have SLC. Here's a Gist of the errors: https://gist.github.com/lee-40square/f292a93bc53297d6f092

I also installed 0.11.8 via nvm since some of the error indicated that might be an issue but in that case SLC doesn't work. But when I switch back to 0.12 it works fine.

Anyway, seem we can probably close this issue.

**Comment by rmg** [comment]
Each version of node you install with `nvm` get's its own world in which global modules are installed, so if you `nvm use 0.12.0` and then `npm install -g strongloop` then `slc` will _only_ be in your PATH when you do `nvm use 0.12.0`. I've also noticed in my own `nvm` use that it uses the system node as the default if you don't tell it otherwise, so when you do `nvm install x.y.z` you then need to do `nvm alias default x.y.z` to have that be the version you get when you load a new shell.

Also, because it operates on the shell environment itself, changes in one shell/terminal are not reflected in any other shell/terminal.
