### ISSUE TITLE
Reinstall of strongloop, slc pm-install does not create /var/lib/strong-pm

### ISSUE THREAD

**Issue by notbrain** [strongloop/strongloop#244]
Apologies if this is not applicable here, but I've just upgraded to 5.0.0 and our apps are no longer spawning with strong-pm. See [strong-pm issue 270](https://github.com/strongloop/strong-pm/issues/270), strange syntax error when I simply try to run the upstart job. 

But also now that I've attempted a fresh global install of strongloop, a subsequent `sudo slc pm-install` no longer knows how to create the /var/lib/strong-pm directory.

This is after a complete removal of strongloop and deleting /var/lib/strong-pm:

    $ sudo npm install -g strongloop
    ...
    $ sudo slc pm-install
    Error installing service 'strong-pm': ENOENT, open '/var/lib/strong-pm/env.json'

A manual creation of `/var/lib/strong-pm` (+ `chown -R strong-pm:strong-pm`) seems to have fixed it and allowed the upstart job to start.

**Comment by rmg** [comment]
https://github.com/strongloop/strong-pm/issues would be more appropriate in this case :-)

Or possibly https://github.com/strongloop/strong-service-install since that functionality was extracted from strong-pm. Either a regression was introduced in the process or there's a hole in the tests. If I recall the code correctly, it is probably assuming that if the user exists and their $HOME is set, then that directory already exists.
