### ISSUE TITLE
miss modules minkelite

### ISSUE THREAD

**Issue by faizalpribadi** [strongloop/strongloop#246]
Hello strongloop guys, after i created the project with strongloop, i try to run gui managament `Arc` but on my system i have missing modules `minkelite` after run command `slc arc` 

here is miss modules : 
```
module.js:338
    throw err;
    ^
Error: Cannot find module '/usr/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

ok this is no big problem, but i hope strongloop team fix this issue, thanks :+1:

**Comment by rmg** [comment]
Did you run `npm install -g strongloop` as root (or with sudo)? If so, try reinstalling with `--unsafe-perm` and see if that helps.

**Comment by rmg** [comment]
For reference, my suggestion is based on mapbox/node-pre-gyp#165 which is known to manifest in sqlite3.

**Comment by faizalpribadi** [comment]
i run this command ` sudo npm install -d -g --unsafe-perm strongloop` to install strongloop 
yep, this is about permission , i got it with the normal user
```
Failed to start embedded process manager!
{ [Error: EACCES, unlink '/home/iCal/github/restloop/.strong-pm/env.json']
  errno: -13,
  code: 'EACCES',
  path: '/home/iCal/github/restloop/.strong-pm/env.json' }
```

i run everytime with sudo when i launch arc, ok, no problem, thanks for quick response @rmg :+1:

**Comment by Alan01252** [comment]
For anyone who gets here with this problem

I fixed with following steps

- sudo npm install -g sqllite3
- mkdir -p /usr/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v14-linux-x64
- cp cp /usr/lib/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node /usr/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node

Then run slc as root

**Comment by yswai** [comment]
Solution above works for Win7 x64 as well.

1. npm install -g sqlite3
2. copy folder C:\Program Files (x86)\nodejs\node_modules\sqlite3\lib\binding\node-v14-win32-x64
3. paste into folder into C:\Users\YSW\AppData\Roaming\npm\node_modules\strongloop\node_modules\minkelite\node_modules\sqlite3\lib\binding

**Comment by smartmouse** [comment]
we do not have root access, is there any workaround without root?

**Comment by rmg** [comment]
The only reason root access is required for the workarounds is because root was used for installation.

**Comment by smartmouse** [comment]
You know what, I just ran into the same error on slc arc with a very different reasons and fixes on a different platform. I want to share it here for awareness.
I am on a recently upgrade SLES 11 SP4 ( the gcc compiler is 4.8.3),-- zlinux platform 64 bit Node 4.x
I do npm install -g strongloop (the usual thing )
Then I do slc arc inside a folder.
I got into the exact error.
The cause is my g++ version is still the old one 4.3.x
Once I fix the g++ to be 4.8.3, the issue was gone.
slc arc works like a charm now.

**Comment by prusanoff** [comment]
Hey guys so from the jist of it i understand it as the i have a different line version of linux so it cant find the driver i have it installed but instead of having 'node-v46-linux-x64/node_sqlite3.node' i have 'node-v11-linux-x64' so just copy it over and good to go?

**Comment by rmg** [comment]
@prusanoff that sounds more like you installed using an older version of node and then upgraded node. Based on the numbers, I'd guess you changed from node v0.10.x to v4.x. You should run `npm rebuild -g strongloop` in that case and expect a bunch of warnings and error messages as it tries to build a bunch of native addons that don't support node 4.x yet.

**Comment by prusanoff** [comment]
@rmg  When i first installed node npm together yes it was v 0.10x however i upgraded it right away to v4. This was the most practical way to install node and also following the instructions on node's site

**Comment by HuemanF** [comment]
For anyone who gets here with this problem

I fixed with following steps

sudo npm install -g sqllite3       <---------------extra l in sqlite3  :) cost me 10 min
