### ISSUE TITLE
gyp ERR! stack Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by VaibhavAjayGupta** [strongloop/strongloop#248]
I have updated my node version to 4.0.0 and now trying to update my strongloop version(npm install -g strongloop) but keeps on getting following error: (current  version of my strongloop is 5.0.0)

syslog.target.mk:90: recipe for target 'Release/obj.target/syslog/syslog.o' failed
make: *** [Release/obj.target/syslog/syslog.o] Error 1
make: Leaving directory '/home/vaibhav/.nvm/versions/node/npm-global/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-supervisor/node_modules/strong-fork-syslog/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vaibhav/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/home/vaibhav/.nvm/versions/node/v4.0.0/bin/node" "/home/vaibhav/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vaibhav/.nvm/versions/node/npm-global/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-supervisor/node_modules/strong-fork-syslog
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok

**Comment by rmg** [comment]
This is fixed on git (spanning multiple repositories) but not everything has made it to npm quite yet.

Hold tight!

**Comment by VaibhavAjayGupta** [comment]
ok

**Comment by aj2050** [comment]
any updates on these errors now available on git ?

**Comment by rmg** [comment]
I should have clarified up front that this error should not be causing the installation to fail. strong-fork-syslog is an optional dependency of strong-supervisor.

@aj2050 It was recently replaced with modern-syslog (strongloop/strong-supervisor#155) in order to support iojs-3/node-4. Because syslog is still inherently incompatible with Windows, it remains an optional dependency.

**Comment by sam-github** [comment]
To be clear, this is a warning, not an error, because the dependency is optional.

**Comment by rmg** [comment]
I've dug into this and this specific error isn't something that will be fixed.
 - this particular dependency is optional
 - it is part of an internal version of strong-pm that is used by strong-arc and is scheduled for removal
 - the functionality that is removed by this strong-fork-syslog not compiling isn't accessible via strong-arc anyway
 - none of the warning messages printed out during `npm install -g strongloop` under node-v4.0.0 are fatal

I'm closing this, since the parts that can be fixed have been fixed and released and the parts that can't will slowly disappear as optional dependencies are updated throughout the node ecosystem.

**Comment by VaibhavAjayGupta** [comment]
@rmg and @sam thanks for the help.
