### ISSUE TITLE
Can't install on Node 4.2.2/5.0.0

### ISSUE THREAD

**Issue by darokel** [strongloop/strongloop#271]
This is what I get when I try to install Strongloop on OSX El Capitan

https://gist.github.com/darokel/cab94d0dd59a7cbfc91f

**Comment by sam-github** [comment]
That's strange, strong-fork-syslog is no longer a dependency of strongloop, but its showing up in your build: `.nvm/versions/node/v5.0.0/lib/node_modules/strongloop/node_modules/strong-fork-syslog`.

Its possible you are stuck on a previous version, the beginning of the npm-debug.log would tell me what version was being installed of strongloop, but its missing. A gist, http://gist.github.com, is a good way to include the entire `npm-debug.log` file without overwhelming a github issue.

Could you clear your npm cache, `npm cache clear`, and try again?

**Comment by darokel** [comment]
I still haven't had any success after cleaning the cache. The `npm-debug.log` doesn't give much (one wasn't even generated after the installation). It only generated when I ran `npm issues` and this was the ouput: 

https://gist.github.com/darokel/41e445c4d8f85c6c3aa5

**Comment by rmg** [comment]
There was a bug in npm@3 that was [fixed in 3.3.7](https://github.com/npm/npm/commit/2289234e11b30c878585aebee68d4a3a5bd63cce), the version just after the one you are running. The problem was that the optional sub-dependencies were not being treated as optional so when they failed to install (like strong-fork-syslog does on node-4), they would cause the entire install to fail.

For resolving this you can either `npm install -g npm@latest` for a 3.x that works or `npm install -g npm@latest-2` to install a 2.x that works.

The error in your second gist about clearing the cache suggests you ran `npm cache` (which defaults to be `npm cache .`) from your home directory and npm didn't like it. It would probably be easier to just `rm -rf ~/.npm` since that is the npm cache directory.

**Comment by darokel** [comment]
Yup, upgrading to `npm install -g npm@latest` worked. Thanks!
