### ISSUE TITLE
"Bundling dependencies" page in the documentation is outdated

### ISSUE THREAD

**Issue by MrOrz** [strongloop/strongloop#294]
The documentation page: https://docs.strongloop.com/display/SLC/Bundling+dependencies

`.npmignore` and `.gitignore` are mentioned in the documentation, however in the most recent implementation (strongloop v6.0.0 w/ strong-build v2.1.0), `slc build --pack` uses [strong-pack](https://github.com/strongloop/strong-pack), which almost does nothing but packing the whole directory into a tarball. It seems that `slc` tools does not provide any method to exclude files from the bundle, so developers would probably have to write their own packaging scripts.

Also, the documentation page mentioned `slc build --bundle`, which is obsolete as well.

**Comment by crandmck** [comment]
@sam-github I can see that the `--bundle` option is gone.  Should I just remove the above-mentioned doc altogether?

> It seems that slc tools does not provide any method to exclude files from the bundle, so developers would probably have to write their own packaging scripts.

Should docs say that?  Or is there a better recommendation?

**Comment by MrOrz** [comment]
> Should docs say that? Or is there a better recommendation?

I think [the doc](https://docs.strongloop.com/display/SLC/Bundling+dependencies) should be clear about what slc does and does not do.
Currently it mentioned a lot of functionality that is attractive to developers, but as they dig in, they would find out that the doc gives nothing but broken promises.

**Comment by sam-github** [comment]
@MrOrz sorry, the docs are lagging behind the source (because we forgot to notify @crandmck).

Feel free to install an older version of strong-build - it implements all those features. Also, you are free to use `npm pack` directly, since the output of strong-build is compatible with it. Either tool can be used to produce input for strong-pm (or indeed, to publish to npmjs.org).

Our users found the features we removed to be anti-features. Much of what strong-build was try to avoid broken npm pack features. For example, your build products should always be in your .gitignore, but your build products should alwasy be deployed, but npm pack defaults to not packing what is in .gitignore... Not helpful.

Note that strong-pack/build is not frozen... if you have some compelling use-case, please bring it up, we may be able to suggest a way to do it, or we may find that it suggests a featue we should implement.

**Comment by crandmck** [comment]
I updated https://docs.strongloop.com/display/SLC/Bundling+dependencies.  @MrOrz I hope (and believe) that it now accurately reflects what the tool does currently; PTAL.

**Comment by MrOrz** [comment]
:+1: thanks for the timely update!
