### ISSUE TITLE
strongloop with mongodb unknown id

### ISSUE THREAD

**Issue by ZYTRIXNARASIMHA** [strongloop/strongloop#335]
HI team,

We are using strongloop with mongodb for one of our client. We are facing an issue with strongloop when mongodb id is having only numbers. We are unable access that record and even unable to delete or update. 
Below is the error we are getting.
"name": "Error",
    "status": 404,
    "message": "Unknown  id \"585511374780906341303131\".",
    "statusCode": 404,
    "code": "MODEL_NOT_FOUND",

We are looking for a fix with out modifying the node modules.
Thanks in advance.

**Comment by superkhau** [comment]
@ZYTRIXNARASIMHA Can you provide a sample repo for us to reproduce the issue on our end? See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

@cgole @ritch Priority and should we pass this off to @kjdelisle since @strongloop/sq-lb-apex is taking care of lb-con-mongodb ATM.

cc @kjdelisle

**Comment by superkhau** [comment]
@cgole This repo needs proper labels too.
